FROM node:20-alpine
WORKDIR /app
LABEL org.opencontainers.image.source=https://github.com/Seechange-edu/speaking-exercise-frontend

ENV NODE_ENV production
ENV PORT 3000

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001
USER nextjs

COPY --chown=nextjs:nodejs public /app/public/
COPY --chown=nextjs:nodejs ./.next/standalone /app/
COPY --chown=nextjs:nodejs ./.next/static /app/.next/static/

EXPOSE 3000
CMD ["node", "server.js"]